# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-06 07:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='daqu',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('level', models.IntegerField()),
                ('duanwei', models.CharField(max_length=10)),
                ('zongchangci', models.IntegerField()),
                ('huochengchangci', models.IntegerField()),
                ('daqu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DB_site.daqu')),
            ],
        ),
    ]
