# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-15 16:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DB_site', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='duanwei',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('duanwei', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='shengchang',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('zongchangci', models.IntegerField()),
                ('huochengchangci', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='huochengchangci',
        ),
        migrations.RemoveField(
            model_name='user',
            name='zongchangci',
        ),
        migrations.AlterField(
            model_name='user',
            name='duanwei',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DB_site.duanwei'),
        ),
        migrations.AddField(
            model_name='shengchang',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DB_site.user'),
        ),
    ]
